---
- name: AAP-10793
  hosts: localhost
  gather_facts: false
  collections:
    - cba.aap
  roles:
    - postdeploy
  tasks:
    - name: Including postdeploy
      ansible.builtin.include_role:
        name: cba.aap.postdeploy
