- name: Fact Gathering test
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Re-run setup to activate custom facts
      ansible.builtin.setup:
        gather_subset:
          - 'all'
          - '!facter'
          - '!ohai'
        filter: ansible_local
    - name: Set a fact with a task
      ansible.builtin.set_fact:
        foo: "bar"
        bar:
          a:
            b:
              - "c"
              - "d"
        cacheable: true
    - name: Debug local facts
      ansible.builtin.debug:
        var: ansible_local
