- name: Fact Gathering test
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Re-run setup to activate custom facts
      ansible.builtin.setup:
        gather_subset:
          - 'all'
          - '!facter'
          - '!ohai'
        filter: ansible_local
    - name: Debug local facts
      ansible.builtin.debug:
        var: ansible_local
