- name: Import user failing due to org assignment
  hosts: localhost
  tasks:
    - name: Import local file
      ansible.controller.import:
        assets: "{{ lookup('file', 'output.json') | from_json() }}"